import type { Metadata } from "next";

import "./globals.css";
import Header from "@/components/Header";
import MouseSpotlight from "@/components/MouseSpotlight";
import { Roboto } from "next/font/google";
import Footer from "@/components/Footer";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <body className={`${roboto.className}`}>
        <div className="relative bg-zinc-950 text-zinc-100 overflow-hidde">
          {/* Mouse spotlight effect */}
          <MouseSpotlight />

          {/* Scan lines effect */}
          <div className="fixed inset-0 pointer-events-none opacity-10 z-50">
            <div className="h-full w-full bg-[repeating-linear-gradient(0deg,transparent,transparent_2px,rgba(34,197,94,0.3)_2px,rgba(34,197,94,0.3)_4px)]" />
          </div>

          <Header />
          <main className="container mx-auto">{children}</main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
