import { montserrat } from "@/libs/font";
import "@/styles/globals.css";

export const metadata = {
	title: "Hyalin",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="fr">
			<body className={montserrat.className}>{children}</body>
		</html>
	);
}
